### ISSUE TITLE
Evaluate SOLID, code smells.

### ISSUE THREAD

**Issue by eferos93** [eferos93/quentin-sdm-exam#40]
Reviewed the entire code and check for violations of SOLID principles and code smells.

**Comment by demirbilek95** [comment]
Just to track up what we detect and how to fix them more efficiently, I prepared a template for code smells and the ones which is quite obvious. You can edit (hopefully) or modify the content when you find new one. Meanwhile we need to work to fix them asap.

Source : https://sourcemaking.com/refactoring/smells

**Comment by demirbilek95** [comment]
> Just to track up what we detect and how to fix them more efficiently, I prepared a template for code smells and the ones which is quite obvious. You can edit (hopefully) or modify the content when you find new one. Meanwhile we need to work to fix them asap.
> 
> Source : https://sourcemaking.com/refactoring/smells

**Code Smells**

1. **Bloaters**
- Long Methods -->  core.Quentin.run, core.Quentin.play, core.Board.getStoneToFillTerritory
- Large Class --> core.Board, core.Quentin
- Primitive Obsession --> Not observed (Prevented by using UI.OutputHandler.Message)
- Long Parameter List --> Not Observed
- Data Clumps --> Not Observed

2. **Object-orientation abusers**
- Switch Statements --> Not observed
- Temporary Fields --> Not observed
- Refused Bequest -> Not observed
- Alternative Classes with Different Interfaces --> Not observed

3. **Couplers**
- Feature Envy --> Need to check more detaily most probably we don't have it.
- Inappropriate Intimacy --> Not observed
- Message Chains --> Not observed
- Middle Man --> Player class has only an extra attribute (name), I admit that this way it's more readable, just wanted to put here we can do the same operation by using Stone, but also we can ignore

4. **Change Preventers**
- Divergent Change, Shotgun Surgery --> Not observed
- Parallel Inheritance Hierarchies --> Not observed

5. **Dispensables**
- Lazy Class --> Not observed
- Data Class --> Not observed
- Duplicate Code --> Not observed
- Dead Code --> Some methods are not used as well as some of the exceptions, we can delete them if we'are not gonna use them at all
-  Speculative Generality --> Not observed
- Comments --> Not observed

**Comment by stefanosimonetto** [comment]
I agree with almost every demirbilek95' s observations, I think that:
-core.Board is definitely too long
-I don't observe feature envy
-The only message chain identified appear when we call the class messages (but I think that with this class is more ordered)
-the only comments are //TODO.

SOLID:
1-Single Responsibility Principle:OK
2-Open-closed Principle (Software entities should be open for extension, but closed for modification) ->(Introduce 
                                         abstraction):OK
3-Liskov Substitution Principle (objects of a superclass shall be replaceable with objects of its subclasses without breaking the 
                                                 application):OK
4-Interface Segregation Principle:OK 
5-Dependency Inversion Principle: OK

**Comment by eferos93** [comment]
> > Just to track up what we detect and how to fix them more efficiently, I prepared a template for code smells and the ones which is quite obvious. You can edit (hopefully) or modify the content when you find new one. Meanwhile we need to work to fix them asap.
> > Source : https://sourcemaking.com/refactoring/smells
> 
> **Code Smells**
> 
> 1. **Bloaters**
> 
> * Long Methods -->  core.Quentin.run, core.Quentin.play, core.Board.getStoneToFillTerritory
> * Large Class --> core.Board, core.Quentin
> * Primitive Obsession --> Not observed (Prevented by using UI.OutputHandler.Message)
> * Long Parameter List --> Not Observed
> * Data Clumps --> Not Observed
> 
> 1. **Object-orientation abusers**
> 
> * Switch Statements --> Not observed
> * Temporary Fields --> Not observed
> * Refused Bequest -> Not observed
> * Alternative Classes with Different Interfaces --> Not observed
> 
> 1. **Couplers**
> 
> * Feature Envy --> Need to check more detaily most probably we don't have it.
> * Inappropriate Intimacy --> Not observed
> * Message Chains --> Not observed
> * Middle Man --> Player class has only an extra attribute (name), I admit that this way it's more readable, just wanted to put here we can do the same operation by using Stone, but also we can ignore
> 
> 1. **Change Preventers**
> 
> * Divergent Change, Shotgun Surgery --> Not observed
> * Parallel Inheritance Hierarchies --> Not observed
> 
> 1. **Dispensables**
> 
> * Lazy Class --> Not observed
> * Data Class --> Not observed
> * Duplicate Code --> Not observed
> * Dead Code --> Some methods are not used as well as some of the exceptions, we can delete them if we'are not gonna use them at all
> * Speculative Generality --> Not observed
> * Comments --> Not observed

Could someone update this?

**Comment by demirbilek95** [comment]
> > > Just to track up what we detect and how to fix them more efficiently, I prepared a template for code smells and the ones which is quite obvious. You can edit (hopefully) or modify the content when you find new one. Meanwhile we need to work to fix them asap.
> > > Source : https://sourcemaking.com/refactoring/smells
> > 
> > 
> > **Code Smells**
> > 
> > 1. **Bloaters**
> > 
> > 
> > * Long Methods -->  core.Quentin.run, core.Quentin.play, core.Board.getStoneToFillTerritory
> > * Large Class --> core.Board, core.Quentin
> > * Primitive Obsession --> Not observed (Prevented by using UI.OutputHandler.Message)
> > * Long Parameter List --> Not Observed
> > * Data Clumps --> Not Observed
> > 
> > 
> > 1. **Object-orientation abusers**
> > 
> > 
> > * Switch Statements --> Not observed
> > * Temporary Fields --> Not observed
> > * Refused Bequest -> Not observed
> > * Alternative Classes with Different Interfaces --> Not observed
> > 
> > 
> > 1. **Couplers**
> > 
> > 
> > * Feature Envy --> Need to check more detaily most probably we don't have it.
> > * Inappropriate Intimacy --> Not observed
> > * Message Chains --> Not observed
> > * Middle Man --> Player class has only an extra attribute (name), I admit that this way it's more readable, just wanted to put here we can do the same operation by using Stone, but also we can ignore
> > 
> > 
> > 1. **Change Preventers**
> > 
> > 
> > * Divergent Change, Shotgun Surgery --> Not observed
> > * Parallel Inheritance Hierarchies --> Not observed
> > 
> > 
> > 1. **Dispensables**
> > 
> > 
> > * Lazy Class --> Not observed
> > * Data Class --> Not observed
> > * Duplicate Code --> Not observed
> > * Dead Code --> Some methods are not used as well as some of the exceptions, we can delete them if we'are not gonna use them at all
> > * Speculative Generality --> Not observed
> > * Comments --> Not observed
> 
> Could someone update this?

I'll try to do it tomorrow. For other guys, feel free to modify if I skip something

**Comment by PascAlex** [comment]
Code Smells

1. Bloaters

- Long Methods --> Quentin.makeMove,, GuiBoardDisplayer.CreateEmptyBoard,, GUI.structureUI,, 

- Large Class -->	Quentin,, GUI,, GUIBoardDisplayer,, ConsoleQuentin

- Primitive Obsession --> Not Observed

- Long Parameter List --> Not Observed

- Data Clumps --> Not Observed

2. Object-orientation abusers

- Switch Statements --> Quentin.makeMove,, GuiBoardDisplayer.CreateEmptyBoard

- Temporary Fields --> Not observed

- Refused Bequest -> Quentin (implements or extends?)

- Alternative Classes with Different Interfaces --> Not observed

3. Couplers

- Feature Envy --> Not observed

- Inappropriate Intimacy --> Not observed

- Message Chains --> Not observed

- Middle Man --> Not observed

4. Change Preventers

- Divergent Change, Shotgun Surgery --> Not observed

- Parallel Inheritance Hierarchies --> Not observed

5. Dispensables

- Lazy Class --> Not observed

- Data Class --> OutputHandler.Message class

- Duplicate Code --> GuiBoardDisplayer.CreateEmptyBoard

- Dead Code --> Not observed

- Speculative Generality --> Not observed

- Comments --> GuiBoardDisplayer.CreateEmptyBoard to make it works with grid starting by 1

**Comment by eferos93** [comment]
To solve Large class

> Code Smells
> 
> 1. Bloaters
> 
> * Long Methods --> Quentin.makeMove,, GuiBoardDisplayer.CreateEmptyBoard,, GUI.structureUI,,
> * Large Class -->	Quentin,, GUI,, GUIBoardDisplayer,, ConsoleQuentin
> * Primitive Obsession --> Not Observed
> * Long Parameter List --> Not Observed
> * Data Clumps --> Not Observed
> 
> 1. Object-orientation abusers
> 
> * Switch Statements --> Quentin.makeMove,, GuiBoardDisplayer.CreateEmptyBoard
> * Temporary Fields --> Not observed
> * Refused Bequest -> Quentin (implements or extends?)
> * Alternative Classes with Different Interfaces --> Not observed
> 
> 1. Couplers
> 
> * Feature Envy --> Not observed
> * Inappropriate Intimacy --> Not observed
> * Message Chains --> Not observed
> * Middle Man --> Not observed
> 
> 1. Change Preventers
> 
> * Divergent Change, Shotgun Surgery --> Not observed
> * Parallel Inheritance Hierarchies --> Not observed
> 
> 1. Dispensables
> 
> * Lazy Class --> Not observed
> * Data Class --> OutputHandler.Message class
> * Duplicate Code --> GuiBoardDisplayer.CreateEmptyBoard
> * Dead Code --> Not observed
> * Speculative Generality --> Not observed
> * Comments --> GuiBoardDisplayer.CreateEmptyBoard to make it works with grid starting by 1

To solve Large Class for Quentin, we can extract a new class for managing the rules.
Regarding GUI and GUIBoardDisplayer it might be difficult, but in general, any Graphical User Interface code tends to be verbose.
