### ISSUE TITLE
Single Responsibility Principle

### ISSUE THREAD

**Issue by eferos93** [eferos93/quentin-sdm-exam#50]
Evaluate and report here eventual Single Responsibility Principle issue

**Comment by eferos93** [comment]
Method `GUI.updateAndFireEvents` has a double reponsibility

**Comment by eferos93** [comment]
Method `ConsoleQuentin.getCoordinatesAndMakeMove` has a double responsibility, but, by separating it into two methods, we would have to move the loop and try/catch up, thus inside `play` method, and risk to make it a bloather.

**Comment by eferos93** [comment]
> Method `GUI.updateAndFireEvents` has a double reponsibility

FIXED

**Comment by wilsonjefferson** [comment]
> Method `ConsoleQuentin.getCoordinatesAndMakeMove` has a double responsibility, but, by separating it into two methods, we would have to move the loop and try/catch up, thus inside `play` method, and risk to make it a bloather.

We may provide the position from the play method, so `getCoordinatesAndMakeMove(Player, stonePosition)` and rename the method `getCoordinatesAndMakeMove` in `performeMove`. Is it reasonable?

**Comment by demirbilek95** [comment]
I think we can put inside of play method, it becomes around 16 lines of code (not sure if it's too long to become a bloather, it was around 15 I guess) but they respect the single responsibility.

**Comment by eferos93** [comment]
> > Method `ConsoleQuentin.getCoordinatesAndMakeMove` has a double responsibility, but, by separating it into two methods, we would have to move the loop and try/catch up, thus inside `play` method, and risk to make it a bloather.
> 
> We may provide the position from the play method, so `getCoordinatesAndMakeMove(Player, stonePosition)` and rename the method `getCoordinatesAndMakeMove` in `performeMove`. Is it reasonable?

Yeah, it's more or less the same I proposed

**Comment by eferos93** [comment]
The problem here is that there is a dependency between the two actions: first, we ask for the coordinates, but we do not make any check on it; then, we pass the result to `makeMove()` and there the check is made: if coordinates are valid, then we are done, otherwise, we have to ask again for the position coordinates and so on.
Concluding, I think it would be better to keep it as it is.

**Comment by eferos93** [comment]
Closing
